language: csharp
solution: 1712884.sln
install:
  - nuget restore 1712884.sln
script:
  - msbuild /p:Configuration=Release 1712884.sln
  - mono ./packages/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./TriangleApp/bin/Release/netcoreapp3.1/TriangleApp.dll